modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

issueTrackerURL="https://github.com/TarantelTM/Roost_Ultimate/issues"

[[mods]]
modId="chicken_roost"
version="${mod_version}"
displayName="Roost Ultimate"
credits="Roost Ultimate"
displayURL="https://www.curseforge.com/minecraft/mc-mods/roost-ultimate" #curse
updateJSONURL="https://raw.githubusercontent.com/TarantelTM/Roost_Ultimate/master/update_curse.json" #curse
#displayURL="https://modrinth.com/mod/roostultimate" #modrinth
#updateJSONURL="https://raw.githubusercontent.com/TarantelTM/Roost_Ultimate/master/update_modrinth.json" #modrinth
logoFile="logo.png"
authors="Tarantel"

[[dependencies.chicken_roost]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
[[dependencies.chicken_roost]]
modId="geckolib"
mandatory=true
versionRange="[4,)"
ordering="AFTER"
side="BOTH"
[[dependencies.chicken_roost]]
modId="crlib"
mandatory=true
versionRange="[1,)"
ordering="AFTER"
side="BOTH"
[[dependencies.chicken_roost]]
modId="connectivity"
mandatory=false
versionRange="[1.20.1-6.8,)"
ordering="AFTER"
side="BOTH"
