# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the the FML version. This is currently 47.
loaderVersion="[1,)" #mandatory
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All Rights Reserved"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="chicken_roost" #mandatory

# The version number of the mod
version="4.2.2" #mandatory

# A display name for the mod
displayName="Roost Ultimate" #mandatory

updateJSONURL="https://raw.githubusercontent.com/TarantelTM/Roost_Ultimate/master/update_curse.json" #curse
displayURL="https://www.curseforge.com/minecraft/mc-mods/roost-ultimate" #curse
#updateJSONURL="https://raw.githubusercontent.com/TarantelTM/Roost_Ultimate/master/update_modrinth.json" #modrinth
#displayURL="https://modrinth.com/mod/roostultimate" #modrinth
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="bh_ru_logo.png" #optional
# A text field displayed in the mod UI
#credits="" #optional
# A text field displayed in the mod UI
authors="Tarantel" #optional


description='''Catch, Breed, get Rich!'''


#[[mixins]]
#config="chicken_roost.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.chicken_roost]]
    # the modid of the dependency
    modId="neoforge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    type="required"
    # The version range of the dependency
    versionRange="[21.1.0,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"
    # Here's another dependency
[[dependencies.chicken_roost]]
    modId="minecraft"
    type="required"
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.21,1.21.1)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chicken_roost]]
    modId="geckolib"
    type="required"
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.chicken_roost]]
    modId="crlib"
    type="required"
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"

#[[dependencies.chicken_roost]]
#modId="bucketlib"
#type="required"
## This version range declares a minimum of the current minecraft version up to but not including the next major version
#versionRange="[1.21-4.1.2.0,)"
#ordering="NONE"
#side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.chicken_roost]
#openGLVersion="[3.2,)"


